package net.atos.si.ma.mt.astreinte.model;

// Generated 26 mars 2015 17:45:30 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Astreinte generated by hbm2java
 */
@Entity
//@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = "aga")
public class Astreinte implements java.io.Serializable {

	/**
	 * 
	 */
	

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	//@GeneratedValue(strategy = GenerationType.SEQUENCE)
	//@SequenceGenerator(name = "generator_Astreinte", sequenceName = "Astreinte_SEQ")
	private Long id;
	private String ref;
	private String sujet;
	private String type;
	private String entite;
	private Date dateD;
	private Date dateF;
	private String demandeur;

	private String ressources;
	@Column(length = 250)
	private String motif;
	@ManyToOne
	private Utilisateur cp;

	@ManyToOne
	private EtatAstreinte etatAstreinte;

	@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
	private List<Intervention> interventions = new ArrayList<Intervention>();

	public Astreinte() {
		super();
	}

	public Astreinte(Boolean b) {
		super();
		if (b)
			this.etatAstreinte = new EtatAstreinte();

	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRef() {
		return ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public String getSujet() {
		return sujet;
	}

	public void setSujet(String sujet) {
		this.sujet = sujet;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getEntite() {
		return entite;
	}

	public void setEntite(String entite) {
		this.entite = entite;
	}

	public Date getDateD() {
		return dateD;
	}

	public void setDateD(Date dateD) {
		this.dateD = dateD;
	}

	public Date getDateF() {
		return dateF;
	}

	public void setDateF(Date dateF) {
		this.dateF = dateF;
	}

	public String getDemandeur() {
		return demandeur;
	}

	public void setDemandeur(String demandeur) {
		this.demandeur = demandeur;
	}

	public String getRessources() {
		return ressources;
	}

	public void setRessources(String ressources) {
		this.ressources = ressources;
	}

	public String getMotif() {
		return motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public EtatAstreinte getEtatAstreinte() {
		return etatAstreinte;
	}

	public void setEtatAstreinte(EtatAstreinte etatAstreinte) {
		this.etatAstreinte = etatAstreinte;
	}

	public Utilisateur getCp() {
		return cp;
	}

	public void setCp(Utilisateur cp) {
		this.cp = cp;
	}

	public List<Intervention> getInterventions() {
		return interventions;
	}

	public void setInterventions(List<Intervention> interventions) {
		this.interventions = interventions;
	}

	@Transient
	public double getCharge() {

		double c = 0;
		for (Intervention intervention : interventions) {
			c += intervention.getCharge();
		}
		return c;
	}

	@Transient
	public double getDuration() {
		double c = 0;
		for (Intervention intervention : interventions) {
			c += intervention.getDuration();
		}
		return c;
	}

}
